### ISSUE TITLE
Address finder showing bus providers

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/tfwm-contact-us#78]
Not sure if this is just an issue because of the API not currently functioning, but the address finder dropdown is showing bus providers...

![Screenshot 2022-06-28 at 12 29 32](https://user-images.githubusercontent.com/68856858/176168013-ca393ace-a247-4529-bd94-c89fb22cfd70.png)

**Comment by saqib-26** [comment]
that was just there to show some data to test, i can remove it
but please suggest what do we show in the dropdown, until the api is not working ..?
